import { useMemo, useState } from "react";
import { PROFILE, projects, publications, researchTags, skills, timeline } from "../data/siteData.js";
import { filterProjects, cx } from "../utils/helpers.js";
import { ButtonLink, CopyEmailButton, ProfilePhoto, ScientificText, Section } from "../components/common.jsx";

function Hero() {
  const quickFacts = [["Education", "M.Sc. Physics, IIT Indore"], ["Location", PROFILE.location]];
  return <section id="top" className="bg-gradient-to-br from-[#fff7f4] via-white to-[#f8fafc] py-16 sm:py-20"><div className="mx-auto grid max-w-6xl gap-10 px-5 sm:px-8 lg:grid-cols-[1.15fr_0.85fr]"><div><p className="mb-3 text-sm font-medium uppercase tracking-[0.18em] text-red-800">High Energy Physics</p><h1 className="text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl">{PROFILE.name}</h1><div className="mt-4 h-1 w-24 bg-red-800" /><p className="mt-4 text-xl text-slate-800">{PROFILE.title}</p><p className="mt-2 text-base text-slate-600">{PROFILE.institute}</p><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-700">{PROFILE.tagline}</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href={PROFILE.cvUrl}>Download CV</ButtonLink><ButtonLink href={PROFILE.githubUrl} variant="secondary">GitHub</ButtonLink><ButtonLink href={PROFILE.linkedinUrl} variant="secondary">LinkedIn</ButtonLink><ButtonLink href={PROFILE.inspireUrl} variant="secondary">Research profile</ButtonLink><CopyEmailButton /></div></div><aside className="border border-red-900/15 bg-[#fffdfb] p-6 shadow-sm"><div className="mx-auto mb-6 aspect-[4/5] max-w-52 overflow-hidden border border-red-900/15 bg-white p-2 sm:max-w-56"><ProfilePhoto /></div><h2 className="text-base font-semibold text-slate-950">Profile</h2><dl className="mt-5 space-y-4">{quickFacts.map(([label, value]) => <div key={label} className="border-t border-red-900/10 pt-4 first:border-t-0 first:pt-0"><dt className="text-xs font-semibold uppercase tracking-[0.14em] text-red-800">{label}</dt><dd className="mt-1 text-sm leading-6 text-slate-800">{value}</dd></div>)}</dl></aside></div></section>;
}

function Research() {
  const cards = [{ title: "Computation and modelling", text: "I enjoy using simulations, numerical methods, and data-driven approaches as tools to test ideas, compare possibilities, and extract physical insight." }, { title: "Instruments and workflows", text: "I am also drawn to the practical side of research, including detector-oriented studies, analysis methods, and frameworks that make scientific work more reliable and reusable." }];
  return <Section id="research" eyebrow="Research" title="Research interests" className="bg-white"><div className="grid gap-5 md:grid-cols-2">{cards.map((card) => <article key={card.title} className="border border-red-900/15 bg-[#fffdfb] p-6"><h3 className="text-lg font-semibold text-slate-950">{card.title}</h3><p className="mt-3 text-sm leading-7 text-slate-700">{card.text}</p></article>)}</div></Section>;
}

function Projects() {
  const [activeTag, setActiveTag] = useState("All");
  const [query, setQuery] = useState("");
  const visibleProjects = useMemo(() => filterProjects(projects, activeTag, query), [activeTag, query]);
  return <Section id="projects" eyebrow="Projects" title="Selected work" className="bg-[#fff7f4]"><div className="mb-8 flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex flex-wrap gap-2">{researchTags.map((tag) => <button key={tag} type="button" onClick={() => setActiveTag(tag)} className={cx("border px-3 py-1.5 text-sm transition", activeTag === tag ? "border-red-900 bg-red-900 text-white" : "border-red-900/25 bg-white text-slate-700 hover:border-red-800 hover:text-red-900")}>{tag}</button>)}</div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search projects" className="w-full border border-red-900/25 bg-white px-3 py-2 text-sm outline-none focus:border-red-900 md:w-72" /></div><div className="space-y-5">{visibleProjects.map((project) => <article key={project.title} className="border border-red-900/15 bg-white p-6 shadow-sm"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="text-xl font-semibold text-slate-950">{project.title}</h3><p className="mt-1 text-sm text-slate-600"><ScientificText text={project.subtitle} /></p></div><span className="w-fit border border-red-900/25 bg-red-50 px-2.5 py-1 text-xs font-medium uppercase tracking-[0.12em] text-red-800">{project.tag}</span></div><p className="mt-4 text-xs font-semibold uppercase tracking-[0.14em] text-red-800">{project.status}</p><p className="mt-3 text-sm leading-7 text-slate-700"><ScientificText text={project.summary} /></p>{project.paperUrl ? <div className="mt-5"><a href={project.paperUrl} target="_blank" rel="noreferrer" className="inline-flex border border-red-900/25 px-3 py-1.5 text-sm font-medium text-red-900 hover:bg-red-50">Open arXiv preprint</a></div> : null}<ul className="mt-5 grid gap-2 md:grid-cols-2">{project.highlights.map((item) => <li key={item} className="flex gap-3 text-sm leading-7 text-slate-700"><span className="mt-3 h-1.5 w-1.5 shrink-0 rounded-full bg-red-800" /><span><ScientificText text={item} /></span></li>)}</ul></article>)}</div>{visibleProjects.length === 0 ? <div className="border border-dashed border-red-900/25 bg-white p-6 text-center text-sm text-slate-600">No project matched this filter.</div> : null}</Section>;
}

function Publications() {
  return <Section id="publications" eyebrow="Publications" title="Papers and manuscripts" className="bg-white"><div className="divide-y divide-red-900/10 border-y border-red-900/10">{publications.map((pub) => <a key={pub.title} href={pub.link} target={pub.link.startsWith("http") ? "_blank" : undefined} rel={pub.link.startsWith("http") ? "noreferrer" : undefined} className="block py-5 hover:bg-red-50/60"><div className="flex flex-col gap-2 sm:flex-row sm:items-baseline sm:justify-between"><h3 className="text-base font-semibold text-slate-950"><ScientificText text={pub.title} /></h3><span className="text-xs font-medium uppercase tracking-[0.12em] text-red-800">{pub.type}</span></div><p className="mt-1 text-sm text-slate-600"><ScientificText text={pub.venue} /></p></a>)}</div></Section>;
}

function SkillsAndTimeline() {
  return <Section id="cv" eyebrow="CV" title="Technical skills and trajectory" className="bg-[#f8fafc]"><div className="grid gap-10 lg:grid-cols-[0.85fr_1.15fr]"><div><h3 className="text-base font-semibold text-slate-950">Selected technical skills</h3><div className="mt-4 flex flex-wrap gap-2">{skills.map((skill) => <span key={skill} className="border border-red-900/20 bg-white px-3 py-1.5 text-sm text-slate-700">{skill}</span>)}</div><div className="mt-6"><ButtonLink href={PROFILE.cvUrl}>Open full CV</ButtonLink></div></div><div className="divide-y divide-red-900/10 border-y border-red-900/10">{timeline.map((item) => <article key={item.title} className="grid gap-3 py-5 sm:grid-cols-[6rem_1fr]"><div className="text-sm font-semibold text-red-900">{item.year}</div><div><h3 className="text-base font-semibold text-slate-950">{item.title}</h3><p className="mt-1 text-sm leading-7 text-slate-700">{item.text}</p></div></article>)}</div></div></Section>;
}

function Contact() {
  return <Section id="contact" eyebrow="Contact" title="Research contact" className="bg-[#fffaf8]"><div className="border border-red-900/15 bg-white p-6 shadow-sm"><p className="max-w-3xl text-sm leading-7 text-slate-700">I am open to technical feedback, research conversations, PhD opportunities, and long-term connections around event generators, HEP software, detector simulation, ROOT based workflows, and physics guided machine learning.</p><div className="mt-6 flex flex-wrap gap-3"><ButtonLink href={`mailto:${PROFILE.email}`}>Email</ButtonLink><ButtonLink href={PROFILE.githubUrl} variant="secondary">GitHub</ButtonLink><ButtonLink href={PROFILE.linkedinUrl} variant="secondary">LinkedIn</ButtonLink><ButtonLink href={PROFILE.inspireUrl} variant="secondary">Research profile</ButtonLink></div></div></Section>;
}

export default function HomePage() {
  return <><Hero /><Research /><Projects /><Publications /><SkillsAndTimeline /><Contact /></>;
}
